test_format = 1.0

[default]

    exclude = ["install.private"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.server_name = "domain.tld"

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.fc2cbb12.name = "Upgrade from 0.12.0"
    test_upgrade_from.fc2cbb12.args.domain = "domain.tld"
    test_upgrade_from.fc2cbb12.args.server_name = "domain.tld"
    test_upgrade_from.fc2cbb12.args.registration = true
