#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

domain=$YNH_APP_NEW_DOMAIN

# Load up registration variables
if [[ $registration -eq 1 ]]
then
        registration_disabled="false"
        really_enable_open_registration="--really-enable-open-registration"
else
        registration_disabled="true"
        really_enable_open_registration=""
fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop" --wait_until="Dendrite is exiting now" --log_path="systemd"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Updating systemd configuration..."

ynh_config_add_systemd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --wait_until="Cleaning old notifications" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
