#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# GENERIC FINALIZATION
#=================================================

ynh_app_config_apply() {
    _ynh_app_config_apply

    if [ "${changed[registration]}" == "true" ]
    then
        if [ $registration -eq 1 ]
        then
            registration_disabled="false"
            really_enable_open_registration="--really-enable-open-registration"
        else
            registration_disabled="true"
            really_enable_open_registration=""
        fi

        ynh_add_config --template="../conf/dendrite.yaml" --destination="$install_dir/dendrite.yaml"
        ynh_add_systemd_config
        ynh_systemd_action --service_name=$app --action="restart" --line_match="Cleaning old notifications" --log_path="systemd"
        ynh_app_setting_set --app=$app --key=registration --value=$registration

    fi
}

ynh_app_config_run $1
