#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

# Allow or deny registration based on is_public
if [ "$registration" -eq "1" ]
then
	registration_disabled="false"
	really_enable_open_registration="--really-enable-open-registration"
	disable_federation="true"
else
	registration_disabled="true"
	really_enable_open_registration=""
	disable_federation="false"
fi

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set --key=server_name --value=$server_name
ynh_app_setting_set --key=domain --value=$domain

#=================================================
# ADD USER TO THE SSL-CERT GROUP
#=================================================

usermod -a -G ssl-cert $app

#=================================================
# CREATE A POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Creating a PostgreSQL database..."

ynh_psql_db_shell <<< "CREATE DATABASE $db_name ENCODING 'UTF8' LC_COLLATE='C' LC_CTYPE='C' template=template0 OWNER $app;"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/build"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

# Create .well-known redirection for access by federation
if yunohost --output-as plain domain list | grep -q "^$server_name$"
then
    ynh_config_add --template="server_name.conf" --destination="/etc/nginx/conf.d/${server_name}.d/${app}_server_name.conf"
fi

#=================================================
# BUILDING SOURCES AND SETTING UP THE SERVER
#=================================================
ynh_script_progression "Building the sources (it will take some time)..."

ynh_go_install

pushd "$install_dir/build"
	# Build the sources
	export GOPATH="$install_dir/build/go"
	export GOCACHE="$install_dir/build/.cache"
	ynh_hide_warnings ynh_exec_as_app CGO_ENABLED=1 go build -trimpath -v -o "$install_dir/bin/" ./cmd/dendrite > /dev/null 2>&1
	ynh_hide_warnings ynh_exec_as_app CGO_ENABLED=1 go build -trimpath -v -o "$install_dir/bin/" ./cmd/create-account > /dev/null 2>&1
	ynh_hide_warnings ynh_exec_as_app CGO_ENABLED=1 go build -trimpath -v -o "$install_dir/bin/" ./cmd/generate-keys > /dev/null 2>&1
popd

ynh_safe_rm "$install_dir/build"
ynh_go_remove

ynh_script_progression "Generating the keys..."

pushd "$install_dir"
	# Generate a Matrix signing key for federation
	./bin/generate-keys --private-key matrix_key.pem
	# Generate a self-signed certificate
	./bin/generate-keys --tls-cert server.crt --tls-key server.key
popd

chown -R $app:root "$install_dir"

#=================================================
## SET STANDARD SETTINGS FROM DEFAULT CONFIG
#=================================================

guests_disabled="true"
registration_shared_secret=""
enable_registration_captcha="false"
ynh_app_setting_set --key=registration_disabled --value=$registration_disabled
ynh_app_setting_set --key=disable_federation --value=$disable_federation
ynh_app_setting_set --key=guests_disabled --value=$guests_disabled
ynh_app_setting_set --key=registration_shared_secret --value=$registration_shared_secret
ynh_app_setting_set --key=enable_registration_captcha --value=$enable_registration_captcha

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="dendrite.yaml" --destination="$install_dir/dendrite.yaml"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."

ynh_config_add_systemd

yunohost service add $app --description="Dendrite Matrix homeserver" --log="/var/log/$app/$app.log" --needs_exposed_ports "$port_tls"

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression "Configuring log rotation..."

mkdir -p /var/log/$app
chown -R $app:root /var/log/$app

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate
# HACKY: Match the weirdly renamed rotated logs.
# Looking at you, matrix-org/dugong library
ynh_replace --match="/var/log/$app/*.log" --replace="/var/log/$app/*.log.????-??-??" --file="/etc/logrotate.d/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --wait_until="Starting external listener" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
